version: "3.8"

services:
  web:
    image: vmw11/node-express-ec2:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
