name: Build & Deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-express-ec2 .

      - name: Publish the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-express-ec2:latest

  deploy:
    runs-on: [node-express-aws-ec2]
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull the Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/node-express-ec2:latest

      - name: Delete the existing Docker container
        run: docker rm -f node-express-ec2 || true

      - name: Run the Docker container
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker-compose up --build -d
